#!/bin/bash
### BEGIN INIT INFO
# Provides:          ssl
# Required-Start:    apache2
# Required-Stop:     apache2
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Generates SSL certs if they don't exist.
# Description:       Generates the SSL certs used by other servers on the
#                    node.  Takes advantage of persistent storage in ByzPi.
### END INIT INFO

# Tests for the presence of /etc/ssl/server.[crt,key] files, and generates
# them if they don't exist.

# TODO:
# - Detect whether or not the cert has expired, and if so torch them and make
#   new ones.

# Set up some variables to make things easier to maintain.
OPENSSL=/usr/bin/openssl
SERVER_DIR=/etc/ssl
PRIVATE_KEY=$SERVER_DIR/private/server.key
CERT_SIGN_REQ=$SERVER_DIR/server.csr
CERT=$SERVER_DIR/certs/server.crt

# Test to see if mod_ssl has been enabled.
if [ ! -f /etc/apache2/mods-enabled/ssl.conf ]; then
	echo "Enabling mod_ssl..."
	/usr/sbin/a2enmod ssl
fi

case "$1" in
    start)
	# Test for the presence of the server cert.  If it exists we don't
	# have to do anything, so terminate the initscript and start over.
	if [ -f $CERT ]; then
	    echo "SSL certificate exists."
	    exit 0
	    fi

	# Server certificate not found.  We may as well blow everything away
	# and start over because any files left won't match up, anyway.
	rm -f $PRIVATE_KEY $CERT_SIGN_REQ $CERT

	# Generate the private key.
	echo "Generating private key."
	$OPENSSL genrsa -out $PRIVATE_KEY 2048

	echo "Generating certificate signing request."
	$OPENSSL req -utf8 -new -key $PRIVATE_KEY -out $CERT_SIGN_REQ \
            -sha512 -batch

	echo "Signing certificate."
	$OPENSSL x509 -req -days 730 -in $CERT_SIGN_REQ -signkey $PRIVATE_KEY \
	    -out $CERT -sha512

	echo "Making permissions on cert files usable."
	chmod 0644 $PRIVATE_KEY $CERT_SIGN_REQ $CERT
	chmod 0755 /etc/ssl/private
	;;
    stop)
	# This is a no-op to prevent the shutdown process from carping.
	;;
    status)
	echo "SSL related files that exist on this node:"
	ls -alF $PRIVATE_KEY $CERT_SIGN_REQ $CERT
	;;
    *)
        echo "Usage: $0 [start|stop|status]"
esac

